USE [master]
GO

/****** Object:  Database [PM01Examen]    Script Date: 05.07.2022 15:38:18 ******/
CREATE DATABASE [PM01Examen]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Pawnshop', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Pawnshop.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Pawnshop_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Pawnshop_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PM01Examen].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PM01Examen] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PM01Examen] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PM01Examen] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PM01Examen] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PM01Examen] SET ARITHABORT OFF 
GO

ALTER DATABASE [PM01Examen] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PM01Examen] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PM01Examen] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PM01Examen] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PM01Examen] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PM01Examen] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PM01Examen] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PM01Examen] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PM01Examen] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PM01Examen] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PM01Examen] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PM01Examen] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PM01Examen] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PM01Examen] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PM01Examen] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PM01Examen] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PM01Examen] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PM01Examen] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [PM01Examen] SET  MULTI_USER 
GO

ALTER DATABASE [PM01Examen] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PM01Examen] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PM01Examen] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PM01Examen] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PM01Examen] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PM01Examen] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [PM01Examen] SET QUERY_STORE = OFF
GO

ALTER DATABASE [PM01Examen] SET  READ_WRITE 
GO

